In [8]:
#Q1 :Create an array of numbers from 0 to 11 and reshape it into a 3x4 matrix.
import numpy as np
nrr=np.arange(12)
rearr_nrr=nrr.reshape((3,4))
print(rearr_nrr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
#Q2 Given arr = np.arange(24), reshape it into: (6,4) and (2,3,4). 
#Explain why some shapes are valid and others are not
arr=np.arange(24)
try:
    rearr_arr=arr.reshape(6,4) 
    
    print(rearr_arr)
    rearr_arr=arr.reshape(2,3,4)
    print(rearr_arr)
    rearr_arr=arr.reshape(6,5) #The number of elements is 24 and it has to be matched with the dimensions of the reshaped matrix.
    print(rearr_arr)
except ValueError:
    print("You cannot reshape this matrix into what you wanted")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
You cannot reshape this matrix into what you wanted


In [17]:
#Q3 Given a = np.array([[10,20,30],[40,50,60],[70,80,90]]) : Access the element 50, the #entire second row and the entire third column
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[1,1])
print(a[1,:])
print(a[:,2])

50
[40 50 60]
[30 60 90]


In [23]:
#Q4 Using the same array a:Slice the first two rows and first two columns.Slice the last two rows and last columns.
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[:2, :2])
print(a[1:,1:])

[[10 20]
 [40 50]]
[[50 60]
 [80 90]]


In [27]:
#Q5Create a 1D array of numbers from 0 to 9. Slice elements from index 2 to 7 and slice every second element.
arr=np.arange(10)
print(arr[2:7])
print(arr[::2])

[2 3 4 5 6]
[0 2 4 6 8]


In [29]:
#Q6:Create an array arr= np.arange(10). Make a view and change the first element to 100.
#Make a copy and change the first element to 200.
#Explain the difference in the original array after each operation.
arr= np.arange(10)
x=arr.view() #a new array which is connected to the original set and can be changed by the change of arr
arr[0]=100
print(arr)
print(x)
y=arr.copy() # a new array which has an exact same elements with arr and is not able to be change by the change of arr
arr[0]=200
print(arr)
print(y)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[200   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [37]:
#Q7:Create a 4x4 array with numbers from 1 to 16. Extract the submatrix[6,7],[10,11]. Reshape the original array into (8,2).
arr= np.arange(1,17)
print(arr)
arr_4 =arr.reshape(4,4)
print(arr_4)
sub_arr=arr_4[1:3,1:3]
print(sub_arr)
re_arr=arr.reshape(8,2)
print(re_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
